dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - pip install --user cpp-coveralls


git:
    submodules: false
    
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./tests/unit_tests

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
